### ISSUE TITLE
Establishing connection to an other user

### ISSUE THREAD

**Issue by YoussefHachicha** [shepeliev/webrtc-kmp#116]
Hello!
Thank you for this awesome library!

but how can I establish a connection to an other user the docs don't specify how to call an other user, could you provide some more docs on how to do that, that would be very helpfull

**Comment by shepeliev** [comment]
Hello @YoussefHachicha,

Establishing connection between users is out of scope of this library and WebRTC in common. I think this [article](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling) may be usefull.
