### ISSUE TITLE
Latest update?

### ISSUE THREAD

**Issue by sweiss435** [shepeliev/webrtc-kmp#119]
Hello,
trying to get your latest, but I get
* What went wrong:
Execution failed for task ':shared:transformIosMainCInteropDependenciesMetadataForIde'.
> Could not resolve all files for configuration ':shared:iosX64CompilationDependenciesMetadata'.
   > Could not find webrtc-kmp-iosx64-0.125.0.klib (com.shepeliev:webrtc-kmp-iosx64:0.125.0).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/shepeliev/webrtc-kmp-iosx64/0.125.0/webrtc-kmp-iosx64-0.125.0.klib
         https://plugins.gradle.org/m2/com/shepeliev/webrtc-kmp-iosx64/0.125.0/webrtc-kmp-iosx64-0.125.0.jar
         
and these plugins.gradle redirect to jcenter 

don't seem to be here yet?
https://mvnrepository.com/artifact/com.shepeliev/webrtc-kmp-iosx64

**Comment by shepeliev** [comment]
Hello @sweiss435 

As I can see the packages have been published successfully at the Maven repository:

https://repo.maven.apache.org/maven2/com/shepeliev/webrtc-kmp/

Please check your build configuration. The lib must not be searched at the Gradle plugins repository. For instance, I use the following `dependencyResolutionManagement` configuration in my own project:

```kotlin
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}
```

**Comment by sweiss435** [comment]
I have that, not sure what's forcing it to try the old repo

**Comment by sweiss435** [comment]
In any case, I do not see /webrtc-kmp-iosx64-0.125.0 at the link you provided for
https://repo.maven.apache.org/maven2/com/shepeliev/webrtc-kmp/

I don't see anything like the iosx64 in there.  Why is it looking for iOS stuff and why is there none?

**Comment by shepeliev** [comment]
All published artifacts are located at https://repo.maven.apache.org/maven2/com/shepeliev/
iOSX64 target also can be found there https://repo.maven.apache.org/maven2/com/shepeliev/webrtc-kmp-iosx64/

> Why is it looking for iOS stuff

If your build targets the iOS platform, it will fetch the iOS library artifacts from Maven.

As you can see the latest 0.125.0 packages are published in Maven too. 

Please review your build configuration. Definitely, it must not fetch WebRTC KMP from **plugins.gradle.org** as you mentioned before. Try to clean the project then sync it again with IDE.
