### ISSUE TITLE
ScreenShare suport(JS)

### ISSUE THREAD

**Issue by mihai1voicescu** [shepeliev/webrtc-kmp#35]
We kinda need suport for ScreenSharing in JS.

Should be as easy as adding

```
inline fun org.w3c.dom.mediacapture.MediaDevices.getDisplayMedia(): Promise<org.w3c.dom.mediacapture.MediaStream> =
    this.asDynamic().getDisplayMedia()
inline fun org.w3c.dom.mediacapture.MediaDevices.getDisplayMedia(constraints: org.w3c.dom.mediacapture.MediaStreamConstraints): Promise<org.w3c.dom.mediacapture.MediaStream> =
    this.asDynamic().getDisplayMedia(constraints)
```
And

```
    suspend fun getDeviceMedia(streamConstraints: MediaStreamConstraintsBuilder.() -> Unit): MediaStream {
        val constraints = MediaStreamConstraintsBuilder().let {
            streamConstraints(it)
            it.constraints
        }

        val jsStream = window.navigator.mediaDevices.getDisplayMedia(constraints.toJson()).await()
        return MediaStream(jsStream)
    }
```

In the JS `MediaDevices`. So looks very easy for JS.

Soooo:

1. Does this sound OK?
2. Can I send a PR with this?
3. Do we prefer this function only be exposed in JS for the moment or add it to the common interface and use a TODO("Not implemented for this platform yet")?

**Comment by shepeliev** [comment]
1. Sounds great.
2. Sure, PRs are appreciated.
3. Screen sharing is implementable in Android and afaik in iOS too. So I think we could add it in common interface with as you described.
