### ISSUE TITLE
Detecting closed/ended/muted tracks on Android

### ISSUE THREAD

**Issue by mihai1voicescu** [shepeliev/webrtc-kmp#46]
Although there are some Flows that look like they could be used to detect closed/ended/muted tracks (`onRemoveTrack`, `onEnded` and  `onMute`) they don't seem to ever emit values on Android.

Is there any feature currently implemented that can allow me to accomplish this?

If not could you offer some pointers so I can implement it?

**Comment by shepeliev** [comment]
AFAIK neither Android nor iOS WebRTC API doesn't expose those events thus I don't have a clear idea of how to add them properly. For now, I've added `onEnded` event for local `MediaStreamTrack`. It's emitted when  `MediaStreamTrack.stop()` is called. 

And I think we could implement `onMute` event for remote video track in a similar way as it's done in [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc/blob/ec55e5295a78e9e74182617611722b3467623feb/android/src/main/java/com/oney/WebRTCModule/VideoTrackAdapter.java)

**Comment by mihai1voicescu** [comment]
Yes they seem to have copied it from chromium https://github.com/react-native-webrtc/react-native-webrtc/commit/49f678eed157ba95cbd7ec8bc19af1b002bb1513

Unfortunately I was unable to see how they do it now, but this seems like a viable option.

For the `onEnded`/`trackRemoved` event can't we scan after a successful negotiation and see if any tracks were removed?

**Comment by mihai1voicescu** [comment]
Also I think you can also reduce the detection time, because if you have multiple tracks on the same PC and you stop receiving frames on just 1 it indicates with a bigger degree of certainty that it was muted.

**Comment by mihai1voicescu** [comment]
@shepeliev Idea fails to import the latest version of the project. Any ideas how I can fix that :) ?

```
com.intellij.openapi.externalSystem.model.ExternalSystemException: This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2021.1.1 or newer.
```

I have the latest version of Idea.

**Comment by mihai1voicescu** [comment]
Works on latest Android studio 😄

**Comment by shepeliev** [comment]
> For the `onEnded`/`trackRemoved` event can't we scan after a successful negotiation and see if any tracks were removed?

Probably it makes sense. I'll try to make some research next week.

**Comment by mihai1voicescu** [comment]
To be honest the current API (separation of mute/unmute/ended) is not exactly great.

I think it would be best if we have a single StateFlow with the current state.

What do you think @shepeliev ?

**Comment by shepeliev** [comment]
I believe muted/unmuted and ended/live are two different states as the track may be muted, but still `Live`. However, you are right, the API could be more elegant. Looks like sticking to JS API is not a good idea at all.

What do you think about that?

```kotlin
interface MediastreamTrack {
    val id: String
    val kind: MediaStreamTrackKind
    val label: String
    var enabled: Boolean

    val muteState: StateFlow<Boolean>
    val readyState: StateFlow<State>

    fun stop()

    enum class State { Live, Ended }
}
```

Also, I think it would be nice to expose lib's API through interfaces instead of as expect/actual classes.

**Comment by mihai1voicescu** [comment]
So a muted stream is a stream that sends only empty frames (by setting `enabled` to false).
An `ended` stream is one that will no longer generate frames because it's source has stopped(for whatever reason). So an ended stream should theoretically never revert back to Live.

I propose we have 
```
interface MediastreamTrack {
    val id: String
    val kind: MediaStreamTrackKind
    val label: String
    var enabled: Boolean

    val state: StateFlow<State>

    fun stop()

    enum class State { Live, Muted, Ended }
}
```
Each stream starts in Live, if it is disabled (enabled=false) it will go to Muted. It can freely transition back afterwards.
If it it stopped, it is final and will go to the Ended state.

Having a single atomic state is much more safe in a multithreaded environment as it eliminates races and potential caching problems.

On top of that, the Ended state is mutually exclusive with the Muted state, since you need to actually send a stream to have it muted.

What do you think?

**Comment by shepeliev** [comment]
It makes sense. Let's implement it as you propose.

**Comment by mihai1voicescu** [comment]
So, the actual detection of these events seems to not only be incomplete and inconsistent, but completely unimplemented everywhere...

There is a nice way of implementing this using the SPD negotiation:

* Pause from sender -> enabled = false (optionally replace track with null on stream (so it does not send empty packages))
* Pause from receiver -> disable transceiver receiver end + negotiate (optionally set enabled false on sender, so it does not consume resources)
* Close -> remove the track from the SPD + negotiate

Note that this requires the user to gracefully handle the `needsnegociation` event.

You can find examples here:
https://github.com/versatica/mediasoup-client/blob/d5662997e102590256524e827535fb2505c5fb67/src/handlers/Chrome74.ts#L780

The abstraction of Sender and Receiver the authors of mediasoup make seems to be a good idea, at least from a high level point of view (thereby hiding the transceiver).

In my application I need these pause and stop detection, I have already created a very high level library built on this one (abstracts away all webrtc knowledge but it is bound to our signaling framework, which is not yet open sourced) so I am faced with 3 options:
1. Implement pause/stop directly in my lib and leave this one low level
2. Implement in a separate library so we can open source that and leave this one low level
3. Directly implement it here, but will no longer be low level (can be made optional since code stripping should eliminate unused code)

What do you think?

**Comment by shepeliev** [comment]
> After some further research these events seem to be referring to only local tracks. Also they fail to fire when setting `enabled` to `false` on Chrome.
> 
> Can you double check? I attached the test case: [channel.zip](https://github.com/shepeliev/webrtc-kmp/files/8089640/channel.zip)

I've done some tests on Chrome, Firefox, and Safari. The results are here:
- Neither `stop()` nor setting `enabled` doesn't fire any event on any type of tracks (local and remote)
- `unmute` event is fired only for the remote track at the moment it's received in `RTCPeerConnection`'s `ontrack` event

The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event) for `mute`/`unmute` events says:

> The condition that most people think of as "muted" (that is, a user-toggled state of silencing a track) is actually managed using the [MediaStreamTrack.enabled](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled) property, for which there are no events.

And for `ended` [event](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event): 

> ended events fire when the media stream track's source permanently stops sending data on the stream. There are various ways this can happen, including:
>
> - There is no more data left to send.
> - The user revoked the permissions needed for the data to be sent.
> - The hardware generating the source data has been removed or ejected.
> - A remote peer has permanently stopped sending data; pausing media does not generate an ended event.

It looks like those events are fired by some outer reasons, but not by the `MediaStreamTrack` API calls.

I was supposed to make this lib just as a Kotlin Multiplatform facade against platform implementations. And I think it should be consistent with JS implementation as much as possible. So I would implement KMM `MediaStreamTrack` events firing in such way:

- in JS use `onmuted`/`onunmuted`, `onended` events as is, just map them to `StateFlow<State>`
- in Android and iOS for `onmuted`/`onunmuted` events adopt the mentioned ReactNative WebRTC solution

And we have to deal with `onended` events in Android and iOS:
- for the remote track I would not implement this event at all.
- for the local track the source of the outer event could be revoking the permission by the user, though the app is stopped in such a case, so there is no sense to handle it (at least on Android)
- one more event source in Andorid may be `CameraEventsHandler` interface.

Concerning your second question

> 1. Implement pause/stop directly in my lib and leave this one low level
> 2. Implement in a separate library so we can open source that and leave this one low level
> 3. Directly implement it here, but will no longer be low level (can be made optional since code stripping should eliminate unused code)

As I mentioned, this lib was implied as a simple facade. It's really would be great to add some higher-level abstractions around tracks and connections. But there are maybe a lot of approaches how to implement them. Therefore, I guess the better way is to implement separate libraries or frameworks.
