### ISSUE TITLE
Running tests on master fails

### ISSUE THREAD

**Issue by mihai1voicescu** [shepeliev/webrtc-kmp#50]
Running the tests on master on Android fails with:

```
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
```

Any ideas on how I can fix it @shepeliev ? I hope you are doing OK 😄 .

I am trying to add support for IR.

**Comment by shepeliev** [comment]
@mihai1voicescu thanks for asking, I'm okay :) 
At the moment I have no idea.  I'll try to check it tomorrow.
