### ISSUE TITLE
Do not see a way to pass isReliable flag to data channel, seems intermittant 

### ISSUE THREAD

**Issue by sweiss435** [shepeliev/webrtc-kmp#59]
Glad to see you are updating the binaries.  I don't need a sample video app.  More minor updates to bring in the latest webrtc might make it work better for me.

**Comment by shepeliev** [comment]
Thanks for feedback. [Data channel spec](https://w3c.github.io/webrtc-pc/#rtcdatachannel) doesn't expose `isReliable` flag, but reliability mode may be set at the creating channel moment by `maxRetransmits` or `maxPacketLifeTime` properties.

> An [RTCDataChannel](https://w3c.github.io/webrtc-pc/#dom-rtcdatachannel) can be configured to operate in different reliability modes. A reliable channel ensures that the data is delivered at the other peer through retransmissions. An unreliable channel is configured to either limit the number of retransmissions ( [maxRetransmits](https://w3c.github.io/webrtc-pc/#dom-rtcdatachannelinit-maxretransmits) ) or set a time during which transmissions (including retransmissions) are allowed ( [maxPacketLifeTime](https://w3c.github.io/webrtc-pc/#dom-rtcdatachannelinit-maxpacketlifetime) ). These properties can not be used simultaneously and an attempt to do so will result in an error. Not setting any of these properties results in a reliable channel.
