### ISSUE TITLE
Podspec seems to have gone missing

### ISSUE THREAD

**Issue by sweiss435** [shepeliev/webrtc-kmp#68]
After the update, I can't seem to build the project anymore. 
Pre-downloading: `webrtc-kmp` from `https://github.com/shepeliev/webrtc-kmp.git`
[!] Unable to find a specification for 'webrtc-kmp'.
It looks like your example works because the webrtc-kmp source is a module in the same project.  Previously we needed to add 
  pod 'webrtc-kmp', :git => 'https://github.com/shepeliev/webrtc-kmp.git'
to the Podfile, so I think there must have been a .podspec in the project, but that seems to be lacking now.

**Comment by shepeliev** [comment]
Oh, yeah it's gone after refactoring, as I removed WebRTC framework dependancy from repository.
I'm researching now how to compose podspec correctly so it could be used both in `build.gradle.kts` with cocoapods plugin either in Podfile. As I'm newbie in iOS development it takes some time to make it work properly :)

As workaround [Carthage](https://github.com/Carthage/Carthage) may be used with following `Cartfile` content:

```
binary "[../WebRTC.json](https://github.com/shepeliev/webrtc-kmp/blob/main/WebRTC.json)" == 100.0.1
```
