### ISSUE TITLE
Dependency not found for iOS Simulator

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [shepeliev/webrtc-kmp#76]
While trying to use the dependency for my KMM project, I see the following errors:

```
:shared:iosSimulatorArm64Main: Could not resolve com.shepeliev:webrtc-kmp:0.106.0.
Required by:
    project :shared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

```
:shared:iosSimulatorArm64Test: Could not resolve com.shepeliev:webrtc-kmp:0.106.0.
Required by:
    project :shared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

Is there a solution or workaround to this @shepeliev ?

**Comment by shepeliev** [comment]
Are you trying it on Apple M1/M2?

**Comment by renaudmathieu** [comment]
Based on the [compose-multiplatform-ios-android-template](https://github.com/JetBrains/compose-multiplatform-ios-android-template), we declare the following target `iosSimulatorArm64()`.

```kotlin
kotlin {
  android()
  iosX64()
  iosArm64()
  iosSimulatorArm64()
```

It seems that removing the target `iosSimulatorArm64` makes everything work fine. 

We should probably add support to this target :)

**Comment by shubhamsinghshubham777** [comment]
Yes, @shepeliev I'm using an M1 Pro
